version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    env_file:
      - .prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
      build:
        context: .
        dockerfile: dockerfile
      container_name: backend
      restart: always
      environment:
        - PYTHONPATH=/app
      depends_on:
        db:
          condition: service_healthy
        meilisearch:
          condition: service_started
      env_file:
        - .prod.env
      command: >
        sh -c "alembic -c alembic.ini upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  redis:
    container_name: redis
    image: redis:7
      
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app/backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .prod.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  celery:
    build:
      context: .
      dockerfile: dockerfile
    container_name: celery
    environment:
      - PYTHONPATH=/app
      - MODE=PROD
    command: celery -A app.backend.helpers.celery worker --loglevel=INFO --pool=threads
    env_file:
      - .prod.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
      meilisearch:
        condition: service_started

  flower:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flower
    env_file:
      - .prod.env
    command: celery --app app.backend.helpers.celery flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - celery
      - redis

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .prod.env
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafanadata:/var/lib/grafana

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    env_file:
      - .prod.env
    environment:
      - MEILI_HTTP_ADDR=0.0.0.0:7700

volumes:
  postgres_data:
  rabbitmq_data:
  grafanadata:
  prometheusdata:
  meili_data: