"""empty message

Revision ID: 21d31c89a5d7
Revises: dae8acedf0e6
Create Date: 2026-09-04 17:24:22.761790

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '21d31c89a5d7'
down_revision: str | Sequence[str] | None = 'dae8acedf0e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
