"""empty message

Revision ID: eee0e8b3d4c9
Revises: 3955813123d5
Create Date: 2026-10-03 14:30:06.098739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee0e8b3d4c9'
down_revision: Union[str, Sequence[str], None] = '3955813123d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitations', ['resume_id', 'vacancy_id'])
    op.create_unique_constraint(None, 'responses', ['resume_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='unique')
    op.drop_constraint(None, 'invitations', type_='unique')
    # ### end Alembic commands ###
