name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SECRET_KEY: test_secret_key
  MODE: TEST
  DB_HOST: localhost
  DB_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: jjpassword
  POSTGRES_DB: jj
  REDIS_HOST: localhost
  REDIS_PORT: 6380
  KEY_FOR_JWT: SECRET_KEY
  RABBITMQ: amqp://guest:guest@localhost:5672//
  DATABASE_URL: postgresql+asyncpg://postgres:jjpassword@localhost:5432/jj
  GF_SECURITY_ADMIN_USER: test_grafana_user
  GF_SECURITY_ADMIN_PASSWORD: test_grafana_password

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6380:6379

      maildev:
        image: maildev/maildev
        ports:
          - 8080:1080
          - 1025:1025

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations (Alembic)
        env:
          DATABASE_URL: postgresql+psycopg2://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.POSTGRES_DB }}
        run: alembic -c alembic.ini -x db_url="$DATABASE_URL" upgrade head

      - name: Run Tests
        run: pytest